# Generated by Django 4.1.7 on 2023-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField()),
                ('Region', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Product', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
            ],
            options={
                'db_table': 'FoodSales',
            },
        ),
    ]
